### ISSUE TITLE
Question: netbox.create_interface issue.

### ISSUE THREAD

**Issue by n-holmstedt** [mirceaulinic/salt-sproxy#119]
Don't know if this is more of an issue for the original salt-module, but since i'm using your sproxy-version of it: 

The 'create_interface' function seem to missing a required argument. Netbox seem to have implemented interface 'type' as a required field. I reckon this module was implemented for an earlier version of Netbox. 

```
salt-minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/var/cache/salt/minion/extmods/modules/netbox.py", line 110, in _add
        return getattr(getattr(nb, app), endpoint).create(**payload)
      File "/usr/local/lib/python3.7/site-packages/pynetbox/core/endpoint.py", line 287, in create
        ).post(args[0] if args else kwargs)
      File "/usr/local/lib/python3.7/site-packages/pynetbox/core/query.py", line 381, in post
        return self._make_call(verb="post", data=data)
      File "/usr/local/lib/python3.7/site-packages/pynetbox/core/query.py", line 274, in _make_call
        raise RequestError(req)
    pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'type': ['This field is required.']}

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/salt/minion.py", line 1675, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/netbox_init.py", line 29, in load_devices
        __salt__['netbox.create_interface']('ti430940400e460', 'eth0')
      File "/var/cache/salt/minion/extmods/modules/netbox.py", line 775, in create_interface
        nb_interface = _add('dcim', 'interfaces', payload)
      File "/var/cache/salt/minion/extmods/modules/netbox.py", line 111, in _add
        except RequestError as e:  # pylint: disable=undefined-variable
    NameError: name 'RequestError' is not defined
``` 
Adding type to the payload, 'type: virtual', resolves the issue.

**Comment by mirceaulinic** [comment]
Yes,I think  it also needs to import `RequestError` from pynetbox. Would you be able to open a PR to fix this?
