### ISSUE TITLE
AttributeError: 'IPCMessageClient' object has no attribute '_refcount_lock'

### ISSUE THREAD

**Issue by panzerfly** [mirceaulinic/salt-sproxy#134]
Error in running salt-sproxy docker image even on a dummy device.

~# cat /etc/profile | grep sproxy
alias sproxy='f(){ docker run --rm --network host -v /srv/salt/base/pillars:/etc/salt/pillar/ -ti mirceaulinic/salt-sproxy salt-sproxy $@; }; f'

~# cat /srv/salt/base/pillars/top.sls
base:

  'router':
    - dummy

~# cat /srv/salt/base/pillars/dummy.sls
proxy:
  proxytype: dummy

~# sproxy router test.ping
Exception ignored in: <bound method IPCClient.__del__ of <salt.transport.ipc.IPCMessageClient object at 0x7f9535ed22b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 369, in __del__
    with self._refcount_lock:
AttributeError: 'IPCMessageClient' object has no attribute '_refcount_lock'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/usr/local/bin/salt-sproxy", line 8, in <module>
    sys.exit(salt_sproxy())
  File "/usr/local/lib/python3.6/site-packages/salt_sproxy/scripts.py", line 95, in salt_sproxy
    client.run()
  File "/usr/local/lib/python3.6/site-packages/salt_sproxy/cli.py", line 241, in run
    'saltutil.sync_roster', kwarg={'saltenv': saltenv}, print_event=False
  File "/usr/local/lib/python3.6/site-packages/salt/runner.py", line 156, in cmd
    full_return)
  File "/usr/local/lib/python3.6/site-packages/salt/client/mixins.py", line 243, in cmd
    return self.low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/local/lib/python3.6/site-packages/salt/client/mixins.py", line 417, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 929, in fire_event
    self.event.fire_event(data, tagify(tag, base=self.base))
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 721, in fire_event
    if not self.connect_pull(timeout=timeout_s):
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 419, in connect_pull
    io_loop=self.io_loop
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 264, in __new__
    client.__singleton_init__(io_loop=io_loop, socket_path=socket_path)
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 292, in __singleton_init__
    self.unpacker = msgpack.Unpacker(encoding=encoding)
  File "msgpack/_unpacker.pyx", line 317, in msgpack._cmsgpack.Unpacker.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/usr/local/bin/salt-sproxy", line 8, in <module>
    sys.exit(salt_sproxy())
  File "/usr/local/lib/python3.6/site-packages/salt_sproxy/scripts.py", line 95, in salt_sproxy
    client.run()
  File "/usr/local/lib/python3.6/site-packages/salt_sproxy/cli.py", line 241, in run
    'saltutil.sync_roster', kwarg={'saltenv': saltenv}, print_event=False
  File "/usr/local/lib/python3.6/site-packages/salt/runner.py", line 156, in cmd
    full_return)
  File "/usr/local/lib/python3.6/site-packages/salt/client/mixins.py", line 243, in cmd
    return self.low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/local/lib/python3.6/site-packages/salt/client/mixins.py", line 417, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 929, in fire_event
    self.event.fire_event(data, tagify(tag, base=self.base))
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 721, in fire_event
    if not self.connect_pull(timeout=timeout_s):
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 419, in connect_pull
    io_loop=self.io_loop
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 264, in __new__
    client.__singleton_init__(io_loop=io_loop, socket_path=socket_path)
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 292, in __singleton_init__
    self.unpacker = msgpack.Unpacker(encoding=encoding)
  File "msgpack/_unpacker.pyx", line 317, in msgpack._cmsgpack.Unpacker.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
Exception ignored in: <bound method IPCClient.__del__ of <salt.transport.ipc.IPCMessageClient object at 0x7f9535ed2d30>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 369, in __del__
    with self._refcount_lock:
AttributeError: 'IPCMessageClient' object has no attribute '_refcount_lock'

**Versions Report**
~# sproxy -V
Salt Version:
           Salt: 2019.2.0
    Salt SProxy: 2020.3.0

Dependency Versions:
        Ansible: Not Installed
           cffi: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
     junos-eznc: Not Installed
       jxmlease: Not Installed
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
         NAPALM: Not Installed
       ncclient: Not Installed
        Netmiko: Not Installed
       paramiko: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pyeapi: Not Installed
         pygit2: Not Installed
       PyNetBox: Not Installed
          PyNSO: Not Installed
         Python: 3.6.10 (default, Feb 26 2020, 16:40:36)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
            scp: Not Installed
          smmap: Not Installed
        textfsm: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: debian 9.12
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: debian 9.12

Seems that if we build a custom image based on salt-sproxy:2020.3.0 and downgrade msgpack in it from version 1.0.0 to 0.6.2 (pip install msgpack==0.6.2) it works as expected

build a custom image based on the following Dockerfile

~/docker/salt-sproxy-custom# cat Dockerfile
FROM mirceaulinic/salt-sproxy:2020.3.0
RUN pip install msgpack==0.6.2

~/docker/salt-sproxy-custom# cat /etc/profile | grep sproxy
alias sproxy2='f(){ docker run --rm --network host -v /srv/salt/base/pillars:/etc/salt/pillar/ -ti salt-sproxy-custom salt-sproxy $@; }; f'

~/docker/salt-sproxy-custom# sproxy2 router test.ping
[WARNING ] /usr/local/lib/python3.6/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

router:
    True

**Comment by mirceaulinic** [comment]
Solved via ccfad4c.
