### ISSUE TITLE
Unable to get example test.ping working due to name '__opts__' is not defined

### ISSUE THREAD

**Issue by biwhite** [mirceaulinic/salt-sproxy#136]
**Describe the bug**
Attempting to make use of sproxy to reduce memory requirements of lots of proxys.  Running through example in documentation and it doesn't work.

**Steps To Reproduce**

```
# /etc/salt/master

pillar_roots:
  base:
    - /srv/pillar
    - /srv/pillar/devices

# /srv/pillar/top.sls

minion1:
  - dummy

# /srv/pillar/devices/dummy.sls
proxy:
  proxytype: dummy


# salt-run pillar.show_pillar minion1
proxy:
    ----------
    proxytype:
        dummy
```

```
# salt-sproxy minion1 test.ping
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
minion1:
    True
```

```
# locate salt_sproxy
/usr/local/lib/python3.6/dist-packages/salt_sproxy
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0-py3.6-nspkg.pth
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info
/usr/local/lib/python3.6/dist-packages/salt_sproxy/__pycache__
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_modules
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners
/usr/local/lib/python3.6/dist-packages/salt_sproxy/cli.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/parsers.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/scripts.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/version.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/__pycache__/cli.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/__pycache__/parsers.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/__pycache__/scripts.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/__pycache__/version.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_modules/__pycache__
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_modules/netbox.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_modules/__pycache__/netbox.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/ansible.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/file.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/netbox.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/pillar.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__/__init__.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__/ansible.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__/file.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__/netbox.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__pycache__/pillar.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/__init__.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/__pycache__
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/__pycache__/__init__.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/__pycache__/proxy.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/INSTALLER
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/LICENSE
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/METADATA
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/RECORD
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/WHEEL
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/entry_points.txt
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/namespace_packages.txt
/usr/local/lib/python3.6/dist-packages/salt_sproxy-2020.3.0.dist-info/top_level.txt


# locate esxi.py
/usr/lib/python3/dist-packages/salt/config/schemas/esxi.py
/usr/lib/python3/dist-packages/salt/grains/esxi.py
/usr/lib/python3/dist-packages/salt/modules/esxi.py
/usr/lib/python3/dist-packages/salt/proxy/esxi.py
/usr/lib/python3/dist-packages/salt/states/esxi.py
```
**Expected behavior**
test.ping should work.

**Versions Report**
Print the output from ``salt-sproxy -V`` inside the backticks below:

```
Salt Version:
           Salt: 3001
    Salt SProxy: 2020.3.0

Dependency Versions:
        Ansible: Not Installed
           cffi: 1.14.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
     junos-eznc: 2.4.1
       jxmlease: Not Installed
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
         NAPALM: 3.0.1
       ncclient: 0.6.7
        Netmiko: 3.1.1
       paramiko: 2.7.1
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pyeapi: 0.8.3
         pygit2: Not Installed
       PyNetBox: Not Installed
          PyNSO: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
            scp: 0.13.2
          smmap: 2.0.3
        textfsm: 1.1.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-96-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```

**Additional context**

Salt packages coming from saltstack Ubuntu repo:
http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest

Salt-sproxy installed/upgraded with pip3.

**Comment by biwhite** [comment]
This looks like it's specific to salt==3001.

Re-creating on a bare Ubuntu 18.04 container, install via .deb packages, or via pip3, salt==3001 breaks, salt==3000 and prior is good.

```
root@f9be3af83dbc:/srv/pillar# salt-run pillar.show_pillar minion1
proxy:
    ----------
    proxytype:
        dummy
root@f9be3af83dbc:/srv/pillar# salt-sproxy minion1 test.ping
minion1:
    True
root@f9be3af83dbc:/srv/pillar# pip3 install salt==3001
Collecting salt==3001
  Downloading https://files.pythonhosted.org/packages/cc/03/a66a65209aa867c6f8414e5f99a52428400ecc93ab1657102284914a5d52/salt-3001.tar.gz (14.4MB)
    100% |################################| 14.4MB 120kB/s
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Collecting distro (from salt==3001)
  Downloading https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: msgpack!=0.5.5,<1.0.0,>=0.5 in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Collecting pycryptodomex>=3.9.7 (from salt==3001)
  Downloading https://files.pythonhosted.org/packages/bc/97/68a589e4913b5081e365920a9303a712ccc1e6f6f30cafba2f1fc3644f5e/pycryptodomex-3.9.7-cp36-cp36m-manylinux1_x86_64.whl (13.7MB)
    100% |################################| 13.7MB 134kB/s
Requirement already satisfied: pyzmq>=17.0.0 in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from salt==3001)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3001)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3001)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=1.0.0->salt==3001)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3001)
Building wheels for collected packages: salt
  Running setup.py bdist_wheel for salt ... done
  Stored in directory: /root/.cache/pip/wheels/f8/f2/08/8c6cb03bf9e0b780738bd5ce2e0c2c66317cea537ed8c8e58f
Successfully built salt
Installing collected packages: distro, pycryptodomex, salt
  Found existing installation: salt 3000
    Uninstalling salt-3000:
      Successfully uninstalled salt-3000
Successfully installed distro-1.5.0 pycryptodomex-3.9.7 salt-3001
root@f9be3af83dbc:/srv/pillar# salt-sproxy minion1 test.ping
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
minion1:
    True
root@f9be3af83dbc:/srv/pillar# cat /etc/salt/master
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /srv/pillar

root@f9be3af83dbc:/srv/pillar# cat /srv/pillar/top.sls
base:
  minion1:
    - dummy
root@f9be3af83dbc:/srv/pillar# cat /srv/pillar/dummy.sls
proxy:
  proxytype: dummy
root@f9be3af83dbc:/srv/pillar# salt-run pillar.show_pillar minion1
proxy:
    ----------
    proxytype:
        dummy
root@f9be3af83dbc:/srv/pillar# pip3 install salt==3000
Collecting salt==3000
Requirement already satisfied: pycrypto>=2.6.1 in /usr/lib/python3/dist-packages (from salt==3000)
Requirement already satisfied: msgpack!=0.5.5,<1.0.0,>=0.5 in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: pyzmq>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from salt==3000)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=1.0.0->salt==3000)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3000)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3000)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->salt==3000)
Installing collected packages: salt
  Found existing installation: salt 3001
    Uninstalling salt-3001:
      Successfully uninstalled salt-3001
Successfully installed salt-3000
root@f9be3af83dbc:/srv/pillar# cat /srv/pillar/dummy.sls
proxy:
  proxytype: dummy
root@f9be3af83dbc:/srv/pillar# salt-sproxy minion1 test.ping
minion1:
    True
```

**Comment by mirceaulinic** [comment]
Managed to reproduce this. Confirm it's a bug, and reported it upstream as https://github.com/saltstack/salt/issues/57811.

It doesn't look however to affect the behaviour of salt-sproxy, seems more like a cosmetic problem (unless you need the ESXI Proxy Module, probably). If you need to run salt-sproxy with Salt 3001, if that's okay for you, can increase the log level to critical (but you'll of course miss some potentially important information) if you want this noise to go away.

**Comment by mirceaulinic** [comment]
One another way to get rid of this noise without increasing the log level would be disabling the ESXI Grain collection:

```yaml
disable_grains:
  - esxi
```

I'll add a recommendation to the docs, it's a good idea to audit what modules you require in your environment in order to optimise the salt-sproxy (and usual PM as well) execution.

**Comment by mirceaulinic** [comment]
Closing, as the upstream issue has been resolved.
