### ISSUE TITLE
[BUG] NameError: name 'HAS_NETMIKO' is not defined                    

### ISSUE THREAD

**Issue by network-shark** [mirceaulinic/salt-sproxy#220]
Hello @mirceaulinic ,

**Describe the bug**
thanks for your help yesterday in the slack channel. I can now successfully use netmiko.send_command , but I still have no luck running netmiko commands inside an existing napalm session. 

salt-sproxy 'myhost' netmiko.send_command 'show version'

successfully return the show version
so netmiko is installed.... 

**Steps To Reproduce**
salt-sproxy 'myhost' napalm.netmiko_call send_command 'show version'

**Expected behavior**
should return output of show version
```
	Salt Version:                                                    
           Salt: 3000                                            
    Salt SProxy: 2020.3.0                                        
                                                                 
Dependency Versions:                                             
        Ansible: 2.10.5                                          
           cffi: 1.14.0                                          
       dateutil: Not Installed                                   
      docker-py: Not Installed                                   
          gitdb: Not Installed                                   
      gitpython: Not Installed                                   
         Jinja2: 2.11.1                                          
     junos-eznc: 2.2.1                                           
       jxmlease: Not Installed                                   
        libgit2: Not Installed                                   
       M2Crypto: Not Installed                                   
           Mako: Not Installed                                   
   msgpack-pure: Not Installed                                   
 msgpack-python: 0.6.2                                           
         NAPALM: 3.2.0                                           
       ncclient: 0.6.7                                           
        Netmiko: 3.3.2                                           
       paramiko: 2.7.1                                           
      pycparser: 2.19                                            
       pycrypto: 3.9.9                                           
   pycryptodome: Not Installed                                   
         pyeapi: 0.8.3                                           
         pygit2: Not Installed                                   
       PyNetBox: Not Installed                                   
          PyNSO: Not Installed                                   
         Python: 3.7.6 (default, Feb 28 2020, 14:34:05)          
   python-gnupg: Not Installed                                   
         PyYAML: 5.3.1                                           
          PyZMQ: 19.0.0                                          
            scp: 0.13.2                                          
          smmap: Not Installed                                   
        textfsm: 1.1.0                                           
        timelib: Not Installed                                   
        Tornado: 4.5.3                                           
            ZMQ: 4.3.2 
```
Any help is appriciate 
```
    The minion function caused an exception: Traceback (most recent call last):                                                                
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 608, in salt_call 
        ret = sa_proxy.functions[function](*args, **kwargs)                                                                                    
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt/utils/napalm.py", line 480, in func_wrapper       
        ret = func(*args, **kwargs)                                                                                                            
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt/modules/napalm_mod.py", line 544, in netmiko_call 
        netmiko_kwargs = netmiko_args()                                                                                                        
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt/utils/napalm.py", line 480, in func_wrapper       
        ret = func(*args, **kwargs)                                                                                                            
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt/modules/napalm_mod.py", line 446, in netmiko_args 
        if not HAS_NETMIKO:                                                                                                                    
    NameError: name 'HAS_NETMIKO' is not defined                                                                                               
```

**Comment by network-shark** [comment]
Ok , I have troubleshooted it further .  I could not found the commit , but it seems in salt 3000 there was no HAS_NETMIKO inside napalm_mod.py .

After updating to 
Salt Version:             
           Salt: 3003     
    Salt SProxy: 2020.10.2

I'm still not able to get it running, but I think this realtes to salt and not salt-sproxy ? 

```
salt-sproxy --sync-modules -c . 'myhost' napalm.netmiko_args

myhost:
    ----------
    device_type:
        cisco_ios
    host:
        myhost
    keepalive:
        5
    password:
        xxxxx
    timeout:
        60
    username:
        myuser
```
 
```
myhost:
    The minion function caused an exception: Traceback (most recent call last):
      File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 637, in salt_call
        ret = sa_proxy.functions[salt_function](*args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/modules/napalm_mod.py", line 542, in netmiko_call
        return __salt__["netmiko.call"](method, *args, **kwargs)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/loader_context.py", line 72, in __getitem__
        return self.value()[item]
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/loader.py", line 1403, in __getitem__
        func = super().__getitem__(item)
      File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003/lib/python3.7/site-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
```

**Comment by network-shark** [comment]
https://github.com/saltstack/salt/issues/60061
