### ISSUE TITLE
Salt 3003.1 KeyError __runner__ again 

### ISSUE THREAD

**Issue by network-shark** [mirceaulinic/salt-sproxy#246]
@mirceaulinic Hey I'm really sorry I just tested your fix with a simple

```
 salt-sproxy --sync-modules -c . 'router10' net.arp 
 salt-sproxy --sync-modules -c . 'router10' net.cli 'show version'
````
, which works, but if I ran a custom module I still receive errors. 

```
Exception occurred in runner proxy.execute: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/client/mixins.py", line 390, in low
    data["return"] = func(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 1447, in execute
    rtargets_roster = roster_modules[roster](_tgt, tgt_type=_tgt_type)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/python/salt-sproxy/var/cache/salt/master/extmods/roster/file.py", line 40, in targets
    **kwargs
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/renderers/jinja.py", line 79, in render
    tmp_data.get("data", "Unknown render error in jinja renderer")
salt.exceptions.SaltRenderError: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 262, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 482, in render_jinja_tmpl
    decoded_context[key] = value.value()
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader_context.py", line 72, in value
    return loader.pack[self.name]
KeyError: '__runner__'



[INFO    ] Runner completed: 20210702104558268378
[DEBUG   ] Runner return: Exception occurred in runner proxy.execute: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/client/mixins.py", line 390, in low
    data["return"] = func(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 1447, in execute
    rtargets_roster = roster_modules[roster](_tgt, tgt_type=_tgt_type)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/python/salt-sproxy/var/cache/salt/master/extmods/roster/file.py", line 40, in targets
    **kwargs
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/renderers/jinja.py", line 79, in render
    tmp_data.get("data", "Unknown render error in jinja renderer")
salt.exceptions.SaltRenderError: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 262, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 482, in render_jinja_tmpl
    decoded_context[key] = value.value()
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader_context.py", line 72, in value
    return loader.pack[self.name]
KeyError: '__runner__'

```
running salt-sproxy --sync-all -c . 'router01' net.facts

```
(3.7.6/envs/salt3003-1) myuser@XXXX:~/python/salt-sproxy/etc/salt% salt-sproxy --sync-all -c . 'router09' net.facts
Exception occurred in runner proxy.execute: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/client/mixins.py", line 390, in low
    data["return"] = func(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/py376/lib/python3.7/site-packages/salt_sproxy/_runners/proxy.py", line 1447, in execute
    rtargets_roster = roster_modules[roster](_tgt, tgt_type=_tgt_type)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/python/salt-sproxy/var/cache/salt/master/extmods/roster/file.py", line 40, in targets
    **kwargs
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/renderers/jinja.py", line 79, in render
    tmp_data.get("data", "Unknown render error in jinja renderer")
salt.exceptions.SaltRenderError: Traceback (most recent call last):
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 262, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/utils/templates.py", line 482, in render_jinja_tmpl
    decoded_context[key] = value.value()
  File "/home/myuser/.pyenv/versions/3.7.6/envs/salt3003-1/lib/python3.7/site-packages/salt/loader_context.py", line 72, in value
    return loader.pack[self.name]
KeyError: '__runner__'
```

**Comment by mirceaulinic** [comment]
Hi @network-shark - sorry, been away for a while, and only noticed this issue now... is it fixed? Otherwise, let me know and I'll try to look into it soon(-ish). Cheers!

**Comment by network-shark** [comment]
@mirceaulinic No problem I thought you are working hard :-) . I don’t know what I did the last time , but today I was not able to recreate  the issue with 3003.1 and your latest version of salt-sproxy that is why I closed it. If I run into it again I will let you know.
