### ISSUE TITLE
Highstate errors

### ISSUE THREAD

**Issue by kzorba** [mirceaulinic/salt-sproxy#57]
I have set up pillar and a state. Relevant files:

**/etc/salt/master**

```
pillar_roots:
  base:
    - /etc/salt/pillar

file_roots:
  base:
    - /etc/salt
    - /etc/salt/states

#proxy_roster: pillar

# Uncomment below settings to use Ansible inventory as roster
proxy_roster: ansible
roster_file: /etc/salt/inventory

```
**/etc/salt/inventory**
```
all:
  children:
    virtual:
      hosts:
        edge1-us:
          grains:
            role: pe
            site: miami
        edge1-fr:
        edge1-mf:
        edge1-gp:
        edge1-mq:
        edge1-gf:
    physical:
      hosts:
        mx240-lab:
        mx104-lab:
        mx51-lab:
        mx52-lab:
```

**/etc/salt/states/bgp_announcements/init.sls**
```
bgp_announcements_recipe:
  netconfig.managed:
    - template_name: salt://bgp_announcements/templates/announcements.py
    - template_engine: py
#    - debug: True
```
**/etc/salt/states/top.sls**

```
base:
#  'type: physical':
#     - match: pillar
#     - netconfig_bgp_announcements
# All minions with a minion_id that begins with 'mx'
  'mx*':
    - bgp_announcement

```

**Steps To Reproduce**
Running state.apply with the state as the argument works as expected

```
root@salt-sproxy:/# salt-sproxy mx104-lab state.apply bgp_announcements
[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/modules/napalm_network.py:1902: DeprecationWarning: The 'template_user' argument to 'net.load_template' is deprecated and has been ignored

[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/modules/napalm_network.py:1902: DeprecationWarning: The 'template_attrs' argument to 'net.load_template' is deprecated and has been ignored

[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/modules/napalm_network.py:1902: DeprecationWarning: The 'template_group' argument to 'net.load_template' is deprecated and has been ignored

[WARNING ] /usr/local/lib/python3.6/dist-packages/salt/modules/napalm_network.py:1902: DeprecationWarning: The 'template_mode' argument to 'net.load_template' is deprecated and has been ignored

mx104-lab:
    ----------
    netconfig_|-bgp_announcements_recipe_|-bgp_announcements_recipe_|-managed:
        ----------
        __id__:
            bgp_announcements_recipe
        __run_num__:
            0
        __sls__:
            bgp_announcements
        changes:
            ----------
        comment:
            Already configured.
        duration:
            10346.073
        name:
            bgp_announcements_recipe
        result:
            True
        start_time:
            21:45:30.776380
```

Running state.apply with no arguments (highstate) fails with the following exceptions:

```
root@salt-sproxy:/# salt-sproxy '*' state.apply                                                                                                                 [101/99991]
edge1-fr:                            
    ----------                    
    no_|-states_|-states_|-None:                                                                     
        ----------                                     
        __run_num__:                                                                      
            0                 
        changes:                                                                              
            ----------                  
        comment:                                                                             
            No Top file or master_tops data matches found. Please see master log for details.
        name:                                                                                
            No States                            
        result:                     
            False                    
edge1-gp:                         
    ----------                                                                                       
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or master_tops data matches found. Please see master log for details.
        name:
            No States
        result:
            False
edge1-mf:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or master_tops data matches found. Please see master log for details.
        name:
            No States
        result:
            False
edge1-gf:                                                                                                                                                        [58/99991]
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or master_tops data matches found. Please see master log for details.
        name:
            No States
        result:
            False
[ERROR   ] 'autoload_dynamic_modules'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py", line 442, in salt_call
    ret = sa_proxy.functions[function](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 779, in apply_
    return highstate(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 1083, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3933, in call_highstate
    self.load_dynamic(matches)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3441, in load_dynamic
    if not self.opts['autoload_dynamic_modules']:
KeyError: 'autoload_dynamic_modules'
mx51-lab:
    None
[ERROR   ] 'autoload_dynamic_modules'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py", line 442, in salt_call
    ret = sa_proxy.functions[function](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 779, in apply_
    return highstate(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 1083, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3933, in call_highstate
    self.load_dynamic(matches)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3441, in load_dynamic
    if not self.opts['autoload_dynamic_modules']:
KeyError: 'autoload_dynamic_modules'
mx240-lab:                                                                                                                                                       [16/99991]
    None
[ERROR   ] 'autoload_dynamic_modules'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py", line 442, in salt_call
    ret = sa_proxy.functions[function](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 779, in apply_
    return highstate(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 1083, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3933, in call_highstate
    self.load_dynamic(matches)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3441, in load_dynamic
    if not self.opts['autoload_dynamic_modules']:
KeyError: 'autoload_dynamic_modules'
mx104-lab:
    None
[ERROR   ] 'autoload_dynamic_modules'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py", line 442, in salt_call
    ret = sa_proxy.functions[function](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 779, in apply_
    return highstate(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/modules/state.py", line 1083, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3933, in call_highstate
    self.load_dynamic(matches)
  File "/usr/local/lib/python3.6/dist-packages/salt/state.py", line 3441, in load_dynamic
    if not self.opts['autoload_dynamic_modules']:
KeyError: 'autoload_dynamic_modules'
mx52-lab:
    None
edge1-us:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or master_tops data matches found. Please see master log for details.
        name:
            No States
        result:
            False
edge1-mq:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or master_tops data matches found. Please see master log for details.
        name:
            No States
        result:
            False

```
**Expected behavior**
`salt-sproxy '*' state.apply` (highstate) should apply the state to all relevant minions (mx*).

**Versions Report**
Print the output from ``salt-sproxy -V`` inside the backticks below:

```
Salt Version:         
           Salt: 2019.2.2
    Salt SProxy: 2019.10.0        
                      
Dependency Versions:                
        Ansible: 2.9.0
           cffi: 1.11.5
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
     junos-eznc: 2.2.1
       jxmlease: Not Installed
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
         NAPALM: 2.5.0
       ncclient: 0.6.6
        Netmiko: 2.4.2
       paramiko: 2.6.0
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pyeapi: 0.8.2
         pygit2: Not Installed
       PyNetBox: Not Installed
          PyNSO: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.0
            scp: 0.13.2
          smmap: Not Installed
        textfsm: 1.1.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-64-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```

**Additional context**
The environment is a docker container with Ubuntu 18.04 environment, python3 (3.6) salt 2019.2.2 (also tried with salt 2018.3.4)  

**Dockerfile**
```
FROM phusion/baseimage:0.11
MAINTAINER <my mail>

# Install min deps, helpful tools
# NAPALM, salt and salt-sproxy
RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y apt-utils \
  && apt-get install -y wget \
  && apt-get install -y iproute2 iputils-ping \
  && apt-get install -y libxslt1-dev libssl-dev libffi-dev \
  && apt-get install -y python3-dev python3-cffi python3-pip \
  && pip3 --no-cache-dir install salt=="2019.2.2" \
#  && pip3 --no-cache-dir install salt=="2018.3.4" \
  && pip3 --no-cache-dir install napalm napalm-yang \
  && pip3 --no-cache-dir install ansible \
  && pip3 --no-cache-dir install salt-sproxy

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Ports
#EXPOSE 4505 4506

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

```

**Comment by mirceaulinic** [comment]
Hey @kzorba - sorry I've missed this one! Can you give #59 a try to make sure it fixes the issue?

**Comment by kzorba** [comment]
Hi @mirceaulinic , I confirm that your patch works. Highstate works when I replaced proxy.py runner with #59
